#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Contracts\Console\Kernel;

$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$exitCode = $kernel->handle(
    $input = Illuminate\Console\Input::createFromGlobals()
);

$kernel->terminate($input, $exitCode);

exit($exitCode);